-- 選手對戰各隊成績 + 分項成績（官網 person/getfighterscore、apart/getapartscore）。
-- 對戰各隊：官網僅 A 一軍例行賽、逐年無生涯累計。分項：支援 A/C/E + 生涯(9999)。
-- 欄位語義同投打對決：HitCnt=打數(AB)、HittingCnt=安打(H)。

-- 1) 打者 對戰各隊（getfighterscore, defendStation=""）
CREATE TABLE IF NOT EXISTS cpbl.batting_vs_team (
    year             smallint NOT NULL,
    kind_code        text     NOT NULL,
    acnt             text     NOT NULL,
    fight_team_code  text     NOT NULL,
    fight_team_name  text,
    team_no          text,
    total_games      int,
    plate_appearances int,
    at_bats          int,
    hits             int,
    rbi              int,
    runs             int,
    singles          int,
    doubles          int,
    triples          int,
    home_runs        int,
    total_bases      int,
    gidp             int,
    sac_hit          int,
    sac_fly          int,
    bb               int,
    ibb              int,
    hbp              int,
    so               int,
    sb_ok            int,
    sb_fail          int,
    sb_pct           real,
    avg              real,
    obp              real,
    slg              real,
    ta               real,
    ops              real,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (year, kind_code, acnt, fight_team_code)
);

-- 2) 投手 對戰各隊（getfighterscore, defendStation="投手"）
CREATE TABLE IF NOT EXISTS cpbl.pitching_vs_team (
    year             smallint NOT NULL,
    kind_code        text     NOT NULL,
    acnt             text     NOT NULL,
    fight_team_code  text     NOT NULL,
    fight_team_name  text,
    team_no          text,
    total_games      int,
    starts           int,
    closes           int,
    complete_games   int,
    shutouts         int,
    wins             int,
    loses            int,
    save_ok          int,
    save_fail        int,
    holds            int,
    inning_pitched_cnt   int,
    inning_pitched_div3  int,
    whip             real,
    era              real,
    plate_appearances int,
    pitch_cnt        int,
    hits             int,
    home_runs        int,
    bb               int,
    ibb              int,
    hbp              int,
    so               int,
    wild_pitch       int,
    balk             int,
    runs             int,
    earned_runs      int,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (year, kind_code, acnt, fight_team_code)
);

-- 3) 打者 分項成績（getapartscore, position=01）
CREATE TABLE IF NOT EXISTS cpbl.batting_splits (
    year             smallint NOT NULL,
    kind_code        text     NOT NULL,
    acnt             text     NOT NULL,
    item_group_code  text     NOT NULL,
    item_index       int      NOT NULL,
    item_name        text,
    item_note        text,
    plate_appearances int,
    at_bats          int,
    hits             int,
    rbi              int,
    singles          int,
    doubles          int,
    triples          int,
    home_runs        int,
    total_bases      int,
    sac_hit          int,
    sac_fly          int,
    bb               int,
    ibb              int,
    hbp              int,
    so               int,
    ground_outs      int,
    fly_outs         int,
    goao             real,
    avg              real,
    obp              real,
    slg              real,
    ops              real,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (year, kind_code, acnt, item_group_code, item_index)
);

-- 4) 投手 分項成績（getapartscore, position=02）
CREATE TABLE IF NOT EXISTS cpbl.pitching_splits (
    year             smallint NOT NULL,
    kind_code        text     NOT NULL,
    acnt             text     NOT NULL,
    item_group_code  text     NOT NULL,
    item_index       int      NOT NULL,
    item_name        text,
    item_note        text,
    wins             int,
    loses            int,
    starts           int,
    complete_games   int,
    shutouts         int,
    save_ok          int,
    inning_pitched_cnt   int,
    inning_pitched_div3  int,
    plate_appearances int,
    pitch_cnt        int,
    strikes          int,
    balls            int,
    hits             int,
    home_runs        int,
    sac_hit          int,
    sac_fly          int,
    bb               int,
    ibb              int,
    hbp              int,
    so               int,
    wild_pitch       int,
    balk             int,
    runs             int,
    earned_runs      int,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (year, kind_code, acnt, item_group_code, item_index)
);

CREATE INDEX IF NOT EXISTS idx_bvt_acnt ON cpbl.batting_vs_team (acnt, year);
CREATE INDEX IF NOT EXISTS idx_pvt_acnt ON cpbl.pitching_vs_team (acnt, year);
CREATE INDEX IF NOT EXISTS idx_bsplit_acnt ON cpbl.batting_splits (acnt, year);
CREATE INDEX IF NOT EXISTS idx_psplit_acnt ON cpbl.pitching_splits (acnt, year);
